# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('hotel', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Trip'),
        ),
    ]
