# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=20)),
                ('destiantion_picture', models.FileField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=200)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared', models.BooleanField(default=False)),
                ('destination', models.CharField(max_length=200)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('trip_picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('text', models.CharField(max_length=1000)),
                ('sequance_in_trip', models.IntegerField()),
                ('trip', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='organizer.NewTrip')),
            ],
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared', models.BooleanField(default=False)),
                ('destination', models.CharField(max_length=200)),
                ('trip_picture', models.FileField(blank=True, null=True, upload_to='')),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('hotel', models.CharField(blank=True, max_length=200, null=True)),
                ('hotel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('existing_hotel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flight_no', models.CharField(blank=True, max_length=200, null=True)),
                ('flight_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transport_company', models.CharField(blank=True, max_length=200, null=True)),
                ('transport_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('existing_hotel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='organizer.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='organizer.TripType'),
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='organizer.NodeType'),
        ),
        migrations.AddField(
            model_name='newtrip',
            name='trip_type',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='organizer.TripType'),
        ),
        migrations.AddField(
            model_name='newtrip',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
