# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2016, 8, 23, 12, 15, 7, 463348, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
