# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_trip_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2016, 8, 23, 18, 18, 32, 296855, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
