# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_remove_newtrip_trip_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtrip',
            name='trip_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
