# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='flight_no',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
