# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_trip_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
