# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_trip_flight_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='flight_no',
            field=models.CharField(max_length=200),
        ),
    ]
