# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_destination_destiantion_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='destiantion_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
