# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_triptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='organizer.TripType'),
        ),
    ]
