# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_auto_20160831_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
