# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_auto_20160917_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='departure_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='departure_lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
