# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_auto_20160831_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
