# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_auto_20160901_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='existing_hotel_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='flight_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='flight_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotel_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transport_company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transport_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
