# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_auto_20160901_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
