# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0012_auto_20160901_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='node',
            name='trip_type',
        ),
        migrations.AddField(
            model_name='newtrip',
            name='trip_type',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='organizer.TripType'),
        ),
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='organizer.NodeType'),
        ),
    ]
