# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0013_auto_20160901_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='trip',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='organizer.NewTrip'),
        ),
    ]
