# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0014_node_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtrip',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newtrip',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
